using Newtonsoft.Json;

namespace _001_MealGenerator.Models;

public record Meal(
    string IdMeal = "",
    string StrMeal = "",
    object? StrDrinkAlternate = null,
    string StrCategory = "",
    string StrArea = "",
    string StrInstructions = "",
    string StrMealThumb = "",
    string StrTags = "",
    string StrYoutube = "",
    string StrIngredient1 = "",
    string StrIngredient2 = "",
    string StrIngredient3 = "",
    string StrIngredient4 = "",
    string StrIngredient5 = "",
    string StrIngredient6 = "",
    string StrIngredient7 = "",
    string StrIngredient8 = "",
    string StrIngredient9 = "",
    string StrIngredient10 = "",
    string StrIngredient11 = "",
    string StrIngredient12 = "",
    string StrIngredient13 = "",
    string StrIngredient14 = "",
    string StrIngredient15 = "",
    object? StrIngredient16 = null,
    object? StrIngredient17 = null,
    object? StrIngredient18 = null,
    object? StrIngredient19 = null,
    object? StrIngredient20 = null,
    string StrMeasure1 = "",
    string StrMeasure2 = "",
    string StrMeasure3 = "",
    string StrMeasure4 = "",
    string StrMeasure5 = "",
    string StrMeasure6 = "",
    string StrMeasure7 = "",
    string StrMeasure8 = "",
    string StrMeasure9 = "",
    string StrMeasure10 = "",
    string StrMeasure11 = "",
    string StrMeasure12 = "",
    string StrMeasure13 = "",
    string StrMeasure14 = "",
    string StrMeasure15 = "",
    object? StrMeasure16 = null,
    object? StrMeasure17 = null,
    object? StrMeasure18 = null,
    object? StrMeasure19 = null,
    object? StrMeasure20 = null,
    object? StrSource = null,
    object? StrImageSource = null,
    object? StrCreativeCommonsConfirmed = null,
    object? DateModified = null
);
public record Root(List<Meal>? Meals);